# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  #name: SelfHostedH
  vmImage: ubuntu-latest #only for Microsoft-hosted agents

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    node -v
    npm -v
  displayName: 'Check Node and npm versions'


- script: |
    echo "Current directory: %cd%"
    npm install
    npm run build
  displayName: 'Install dependencies and build'
  
- task: CopyFiles@2
  inputs:
      Contents: 'dist/**'
      TargetFolder: '$(build.artifactstagingdirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'vue_dist_file'
    publishLocation: 'Container'