
trigger:
- main

pool:
  #name: SelfHostedH #
  vmImage: ubuntu-latest #only for Microsoft-hosted agents

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    node -v
    npm -v
  displayName: 'Check Node and npm versions'


- script: |
    echo "Current directory: %cd%"
    npm install
    npm run build
  displayName: 'Install dependencies and build'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'dist'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
    
# - task: CopyFiles@2
#   inputs:
#     Contents: 'dist/**'
#     TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'vue_dist_file'
    publishLocation: 'Container'