# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  name: SelfHostedH
  #vmImage: ubuntu-latest #only for Microsoft-hosted agents

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    echo "Current directory: $(pwd)"
    npm install
    npm run build
    echo "Build folder contents:"
    ls -la dist
  displayName: 'Install dependencies and build'